### ISSUE TITLE
Test ID for Android全く表示されません

### ISSUE THREAD

**Issue by Estejin** [fan-ADN/nendSDK-Flutter#2]
onLoaded callback is called, but onReceived() is not called, onFailedToLoad is also not call.

**Comment by Estejin** [comment]
There is no problem for iOS.

**Comment by Estejin** [comment]
import 'package:flutter/cupertino.dart';
import 'package:weather_rain_radar/utils/ad_helper.dart';
import 'package:nend_plugin/nend_plugin.dart';

class MyBanner extends StatefulWidget {
  final AdInfo adInfo;
  const MyBanner(this.adInfo);
  @override
  _MyBannerState createState() => _MyBannerState();
}
class _MyBannerState extends State<MyBanner> {
  late BannerAdController adController;
  BannerSize _bannerSize = BannerSize.type320x50;
  @override
  Widget build(BuildContext context) {
    return Container(
      height: _bannerSize.height,
      child:BannerAd(
        bannerSize: _bannerSize,
        adjustSize: true,
        listener: _eventListener(),
        onCreated: (controller) {
          adController = controller;
          adController.load(spotId: widget.adInfo.spotId, apiKey: widget.adInfo.apiKey);
        },
      ),
    );
  }


  @override
  void initState() {
    super.initState();
  }
  BannerAdListener _eventListener() {
    return BannerAdListener(
      onLoaded: () {
        print('Ads onLoaded:${widget.adInfo.toString()}');
      },
      onReceiveAd: () {
        print('Ads onReceiveAd');
        adController.show();
      },
      onFailedToLoad: () {
        print('Ads failed');
      }
    );
  }
  @override
  void dispose() {
    super.dispose();
    adController.dispose();
  }
}

**Comment by fan-n-kunimoto** [comment]
@Estejin 

Thank you for contact us.

In Android, there was a bug that `onReceived()` is not called. Sorry about that.
Could you try changing the call to `adController.show();` to be called at the timing of `onLoaded()` and see if that solves the problem?

**Comment by Estejin** [comment]
Oh, very thanks.

calling adController.show() in onLoad() is done.

> @Estejin
> 
> Thank you for contact us.
> 
> In Android, there was a bug that `onReceived()` is not called. Sorry about that. Could you try changing the call to `adController.show();` to be called at the timing of `onLoaded()` and see if that solves the problem?
